version: '2'
networks:
    app: ~
services:
    node:
        build: docker/node
        volumes: ['./:/app']
        environment:
         - "TERM=xterm-color"
        logging: { driver: "json-file", options: { max-size: "200k", max-file: "5" } }
        networks: [app]
        privileged: true
        env_file:
         - .env
